spring.application.name=SkijalisteWEB
spring.mvc.view.prefix=/
spring.mvc.view.suffix=.jsp
spring.datasource.url=jdbc:mysql://localhost:3306/skijaliste_db
spring.datasource.username=root
spring.datasource.password=Staza#Vrh26!
spring.datasource.hikari.maximum-pool-size=2
server.servlet.context-path=/Skijaliste
server.port=8080
spring.jpa.hibernate.naming.physicalstrategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
secret_key=moj-tajni-kljuc-za-skijaliste-2026!